# Generated by Django 3.1.7 on 2021-04-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='username',
            field=models.TextField(default=-1, max_length=50),
            preserve_default=False,
        ),
    ]
